// HumWorld - datos de EJEMPLO para la maqueta de la pantalla de noticias.
// Todo lo de este archivo es inventado: medios, titulares, fechas y valores.
// Todavía no existe un contrato de API para "noticias influyentes" (el PDF del
// proyecto exige GET /api/v1/news con esa consulta). Los nombres de los campos
// son una suposición basada en el contrato de sentimiento (valor_humor,
// continente, pais) y deben ajustarse cuando el equipo defina ese contrato.
export const noticiasEjemplo = [
  {
    id: 1,
    titulo: 'Firman acuerdo de paz tras meses de negociación',
    enlace: 'https://example.com/noticia-1',
    fuente: 'Diario Ejemplo Europa',
    continente: 'Europa',
    pais: 'ES',
    categoria: 'Conflicto, guerra y paz',
    fecha_publicacion: '2026-10-02T09:15:00Z',
    valor_humor: 7.5,
  },
  {
    id: 2,
    titulo: 'Crisis energética golpea a la región',
    enlace: 'https://example.com/noticia-2',
    fuente: 'Ejemplo News Asia',
    continente: 'Asia',
    pais: 'IN',
    categoria: 'Economía, negocios y finanzas',
    fecha_publicacion: '2026-10-02T11:40:00Z',
    valor_humor: -6.8,
  },
  {
    id: 3,
    titulo: 'Crecimiento económico supera las expectativas',
    enlace: 'https://example.com/noticia-3',
    fuente: 'Diario Ejemplo Sur',
    continente: 'América del Sur',
    pais: 'CL',
    categoria: 'Economía, negocios y finanzas',
    fecha_publicacion: '2026-10-01T18:05:00Z',
    valor_humor: 5.2,
  },
  {
    id: 4,
    titulo: 'Protestas masivas por el alza de precios',
    enlace: 'https://example.com/noticia-4',
    fuente: 'Ejemplo News África',
    continente: 'África',
    pais: 'NG',
    categoria: 'Política',
    fecha_publicacion: '2026-10-02T07:30:00Z',
    valor_humor: -4.4,
  },
  {
    id: 5,
    titulo: 'Nueva vacuna muestra resultados alentadores',
    enlace: 'https://example.com/noticia-5',
    fuente: 'Diario Ejemplo Norte',
    continente: 'América del Norte',
    pais: 'US',
    categoria: 'Salud',
    fecha_publicacion: '2026-10-01T14:20:00Z',
    valor_humor: 6.1,
  },
  {
    id: 6,
    titulo: 'Incendios forestales obligan a evacuar varias ciudades',
    enlace: 'https://example.com/noticia-6',
    fuente: 'Ejemplo News Oceanía',
    continente: 'Oceanía',
    pais: 'AU',
    categoria: 'Medio ambiente',
    fecha_publicacion: '2026-10-02T03:50:00Z',
    valor_humor: -7.2,
  },
  {
    id: 7,
    titulo: 'La selección local gana el campeonato continental',
    enlace: 'https://example.com/noticia-7',
    fuente: 'Diario Ejemplo Sur',
    continente: 'América del Sur',
    pais: 'AR',
    categoria: 'Deporte',
    fecha_publicacion: '2026-09-30T22:10:00Z',
    valor_humor: 3.9,
  },
  {
    id: 8,
    titulo: 'El parlamento aprueba el presupuesto del próximo año',
    enlace: 'https://example.com/noticia-8',
    fuente: 'Diario Ejemplo Europa',
    continente: 'Europa',
    pais: 'DE',
    categoria: 'Política',
    fecha_publicacion: '2026-10-01T10:00:00Z',
    valor_humor: 0,
  },
]
