// HumWorld - datos de EJEMPLO para la maqueta de la nube de palabras. Todo es inventado.
// Todavía no existe un contrato de API para esta vista (el PDF del proyecto exige
// GET /api/v1/dashboards con la nube de palabras). Supuestos a validar con el equipo:
// - "palabra" y "valor" siguen el esquema TerminoDiccionario del contrato de
//   sentimiento (valor entero entre -10 y +10).
// - "peso" es cuánto influyó la palabra en el humor. Lo debe calcular el backend:
//   el frontend solo lo usa para decidir el tamaño de la letra.
// - "continente: null" representa la nube sin filtro (todo el mundo).
export const palabrasEjemplo = [
  {
    continente: null,
    palabras: [
      { palabra: 'acuerdo', valor: 6, peso: 65 },
      { palabra: 'ataque', valor: -9, peso: 91 },
      { palabra: 'avance', valor: 4, peso: 86 },
      { palabra: 'ayuda', valor: 5, peso: 91 },
      { palabra: 'celebración', valor: 6, peso: 28 },
      { palabra: 'conflicto', valor: -8, peso: 87 },
      { palabra: 'crecimiento', valor: 5, peso: 9 },
      { palabra: 'crisis', valor: -7, peso: 75 },
      { palabra: 'desempleo', valor: -6, peso: 16 },
      { palabra: 'esperanza', valor: 7, peso: 15 },
      { palabra: 'guerra', valor: -10, peso: 12 },
      { palabra: 'incendio', valor: -7, peso: 32 },
      { palabra: 'inflación', valor: -5, peso: 38 },
      { palabra: 'muerte', valor: -9, peso: 84 },
      { palabra: 'paz', valor: 8, peso: 11 },
      { palabra: 'protesta', valor: -4, peso: 67 },
      { palabra: 'récord', valor: 3, peso: 49 },
      { palabra: 'victoria', valor: 7, peso: 64 },
    ],
  },
  {
    continente: 'América del Norte',
    palabras: [
      { palabra: 'acuerdo', valor: 6, peso: 98 },
      { palabra: 'ataque', valor: -9, peso: 40 },
      { palabra: 'celebración', valor: 6, peso: 48 },
      { palabra: 'crecimiento', valor: 5, peso: 37 },
      { palabra: 'crisis', valor: -7, peso: 73 },
      { palabra: 'esperanza', valor: 7, peso: 44 },
      { palabra: 'guerra', valor: -10, peso: 11 },
      { palabra: 'incendio', valor: -7, peso: 16 },
      { palabra: 'paz', valor: 8, peso: 80 },
      { palabra: 'récord', valor: 3, peso: 21 },
      { palabra: 'victoria', valor: 7, peso: 59 },
    ],
  },
  {
    continente: 'América del Sur',
    palabras: [
      { palabra: 'acuerdo', valor: 6, peso: 68 },
      { palabra: 'avance', valor: 4, peso: 56 },
      { palabra: 'ayuda', valor: 5, peso: 98 },
      { palabra: 'esperanza', valor: 7, peso: 58 },
      { palabra: 'guerra', valor: -10, peso: 61 },
      { palabra: 'incendio', valor: -7, peso: 17 },
      { palabra: 'inflación', valor: -5, peso: 80 },
      { palabra: 'muerte', valor: -9, peso: 88 },
      { palabra: 'paz', valor: 8, peso: 33 },
      { palabra: 'récord', valor: 3, peso: 94 },
    ],
  },
  {
    continente: 'Europa',
    palabras: [
      { palabra: 'acuerdo', valor: 6, peso: 67 },
      { palabra: 'ataque', valor: -9, peso: 70 },
      { palabra: 'avance', valor: 4, peso: 30 },
      { palabra: 'ayuda', valor: 5, peso: 95 },
      { palabra: 'conflicto', valor: -8, peso: 79 },
      { palabra: 'crecimiento', valor: 5, peso: 32 },
      { palabra: 'crisis', valor: -7, peso: 65 },
      { palabra: 'esperanza', valor: 7, peso: 73 },
      { palabra: 'guerra', valor: -10, peso: 32 },
      { palabra: 'incendio', valor: -7, peso: 24 },
      { palabra: 'muerte', valor: -9, peso: 61 },
      { palabra: 'récord', valor: 3, peso: 90 },
    ],
  },
  {
    continente: 'África',
    palabras: [
      { palabra: 'acuerdo', valor: 6, peso: 90 },
      { palabra: 'avance', valor: 4, peso: 81 },
      { palabra: 'ayuda', valor: 5, peso: 20 },
      { palabra: 'celebración', valor: 6, peso: 13 },
      { palabra: 'desempleo', valor: -6, peso: 26 },
      { palabra: 'esperanza', valor: 7, peso: 35 },
      { palabra: 'guerra', valor: -10, peso: 64 },
      { palabra: 'inflación', valor: -5, peso: 41 },
      { palabra: 'muerte', valor: -9, peso: 9 },
      { palabra: 'paz', valor: 8, peso: 86 },
      { palabra: 'protesta', valor: -4, peso: 50 },
      { palabra: 'récord', valor: 3, peso: 45 },
      { palabra: 'victoria', valor: 7, peso: 57 },
    ],
  },
  {
    continente: 'Asia',
    palabras: [
      { palabra: 'acuerdo', valor: 6, peso: 87 },
      { palabra: 'avance', valor: 4, peso: 66 },
      { palabra: 'ayuda', valor: 5, peso: 24 },
      { palabra: 'conflicto', valor: -8, peso: 83 },
      { palabra: 'crecimiento', valor: 5, peso: 69 },
      { palabra: 'esperanza', valor: 7, peso: 81 },
      { palabra: 'guerra', valor: -10, peso: 25 },
      { palabra: 'muerte', valor: -9, peso: 57 },
      { palabra: 'paz', valor: 8, peso: 31 },
      { palabra: 'victoria', valor: 7, peso: 88 },
    ],
  },
  {
    continente: 'Oceanía',
    palabras: [
      { palabra: 'avance', valor: 4, peso: 69 },
      { palabra: 'ayuda', valor: 5, peso: 85 },
      { palabra: 'crecimiento', valor: 5, peso: 18 },
      { palabra: 'crisis', valor: -7, peso: 61 },
      { palabra: 'desempleo', valor: -6, peso: 14 },
      { palabra: 'esperanza', valor: 7, peso: 21 },
      { palabra: 'guerra', valor: -10, peso: 21 },
      { palabra: 'incendio', valor: -7, peso: 12 },
      { palabra: 'muerte', valor: -9, peso: 73 },
      { palabra: 'paz', valor: 8, peso: 40 },
      { palabra: 'récord', valor: 3, peso: 38 },
    ],
  },
]
